import Foundation

extension L10n {
    static let chinese: [Key: String] = [
        .appName: "现金记账",
        .appTagline: "专业收据管理工具",
        .newReceipt: "新建收据",
        .history: "历史记录",
        .dashboard: "仪表盘",
        .scan: "扫描",
        .rates: "汇率",
        .settings: "设置",
        .members: "会员",
        .archive: "归档",
        .more: "更多",
        .aiReceiptScanner: "AI 收据扫描（Gemini）",
        .gallery: "相册",
        .camera: "相机",
        .scanBarcode: "扫描条形码",
        .viewScanHistory: "查看扫描记录",
        .receiptDetails: "收据详情",
        .titleField: "标题",
        .placeStoreName: "地点 / 商店名称",
        .address: "地址",
        .locationAddressGPS: "位置地址（GPS）",
        .currency: "货币",
        .category: "类别",
        .paymentType: "付款方式",
        .selectMember: "选择会员",
        .customerName: "客户姓名",
        .customerPhone: "客户电话（可选）",
        .customerEmail: "客户邮箱（可选）",
        .addItems: "添加商品",
        .itemName: "商品名称",
        .quantity: "数量",
        .price: "价格",
        .unitPrice: "单价",
        .total: "合计",
        .item: "商品",
        .discountAndTax: "折扣与税",
        .discountType: "折扣类型",
        .taxPercentOptional: "税率 %（可选）",
        .notes: "备注",
        .notesPageTwo: "备注（第 2 页）",
        .livePreview: "实时预览",
        .digitalSignature: "电子签名",
        .signatureCaptured: "已签名",
        .signatureHint: "已成功应用授权签名",
        .saveAsDefaultSignature: "保存为默认签名",
        .clearAndRedraw: "清除并重画",
        .clear: "清除",
        .generate: "生成",
        .cashMemo: "现金收据",
        .receiptNo: "收据编号",
        .date: "日期",
        .time: "时间",
        .method: "方式",
        .customer: "客户",
        .subtotal: "小计",
        .grandTotal: "总计",
        .discount: "折扣",
        .tax: "税",
        .cashGiven: "实收现金",
        .changeAmount: "找零",
        .note: "备注",
        .savedLocation: "已保存的位置",
        .gps: "GPS",
        .authorizedSignature: "授权签名",
        .scanQRForDetails: "扫描二维码查看详情",
        .thankYouForShopping: "感谢您的惠顾！",
        .searchReceipts: "搜索收据",
        .noReceiptsYet: "暂无收据",
        .noReceiptsHint: "生成的收据将显示在这里。",
        .archived: "已归档",
        .unarchive: "取消归档",
        .delete: "删除",
        .share: "分享",
        .duplicate: "复制",
        .periodToday: "今天",
        .periodWeek: "本周",
        .periodMonth: "本月",
        .periodYear: "本年",
        .periodCustom: "自定义",
        .invoices: "发票",
        .topStore: "热门商店",
        .thisMonth: "本月",
        .avgReceipt: "平均收据",
        .totalItems: "商品总数",
        .topCategory: "热门类别",
        .revenueTrend: "营收趋势",
        .insights: "洞察",
        .notEnoughData: "该时段数据不足",
        .noDataForPeriod: "该时段无数据",
        .liveExchangeRates: "实时汇率",
        .updatedAt: "更新于",
        .refresh: "刷新",
        .quickOverview: "快速概览",
        .todaysSales: "今日销售",
        .todaysRevenue: "今日营收",
        .totalProducts: "商品总数",
        .scansToday: "今日扫描",
        .online: "在线",
        .offline: "离线",
        .rateAPI: "汇率接口",
        .weather: "天气",
        .ratesAt: "汇率",
        .membersDirectory: "会员名录",
        .addMember: "添加会员",
        .editMember: "编辑会员",
        .exportMembers: "导出会员",
        .name: "姓名",
        .phone: "电话",
        .email: "邮箱",
        .noMembersYet: "暂无会员",
        .noMembersHint: "添加会员，以便在收据中重复使用其信息。",
        .appearance: "外观",
        .urduLanguage: "乌尔都语",
        .theme: "主题",
        .themeSystem: "跟随系统",
        .themeLight: "浅色",
        .themeDark: "深色",
        .security: "安全",
        .appLock: "应用锁",
        .appLockHint: "启用密码或指纹以保护应用安全。关闭应用后，重新打开时需要使用 Face ID、Touch ID 或您的密码。",
        .biometrics: "生物识别",
        .customPasscodeLock: "自定义密码锁",
        .customPasscodeHint: "设置一个自定义密码，安全地存储在钥匙串中作为备用。",
        .enterNewPasscode: "输入新密码",
        .confirmNewPasscode: "确认新密码",
        .cancel: "取消",
        .update: "更新",
        .passcodeMismatch: "两次输入的密码不一致。",
        .passcodeTooShort: "密码至少需要 4 位数字。",
        .signature: "签名",
        .createSignature: "创建签名",
        .removeSignature: "删除签名",
        .customCurrency: "自定义货币",
        .addThisCurrency: "添加此货币",
        .googleSignIn: "Google 登录",
        .googleSignInHint: "使用 Google 账户登录，备份将自动上传。",
        .signInWithGoogle: "使用 Google 登录",
        .signOut: "退出登录",
        .backupAndRestore: "备份与恢复",
        .uploadBackup: "上传备份到云端",
        .shareBackupFile: "分享备份文件",
        .restoreFromBackup: "从备份恢复",
        .dataManagement: "数据管理",
        .deleteAllReceipts: "删除所有收据",
        .deleteAllConfirm: "此操作将永久删除本设备上的所有收据，无法撤销。",
        .information: "信息",
        .version: "版本",
        .app: "应用",
        .contactUs: "联系我们！",
        .mail: "邮件",
        .web: "网站",
        .social: "社交",
        .contactResponseNote: "我们会尽快回复。",
        .categoryShopping: "购物",
        .categoryGroceries: "杂货",
        .categoryFood: "餐饮",
        .categoryFuel: "燃油",
        .categoryTravel: "出行",
        .categoryUtilities: "公共事业",
        .categoryHealth: "健康",
        .categoryEducation: "教育",
        .categoryServices: "服务",
        .categoryOther: "其他",
        .methodCash: "现金",
        .methodApplePay: "Apple Pay",
        .methodCard: "银行卡",
        .methodBankTransfer: "银行转账",
        .methodEasypaisa: "Easypaisa",
        .methodJazzcash: "JazzCash",
        .methodCredit: "赊账",
        .discountNone: "无",
        .discountPercentage: "百分比",
        .discountFixed: "固定金额",
        .openOnIPhoneToSync: "请在您的 iPhone 上打开 Cash Memer 以同步收据",
        .openOnIPhoneToSyncRates: "请在您的 iPhone 上打开 Cash Memer 以同步汇率",
        .syncedJustNow: "刚刚已同步",
        .pageTwo: "第 2 页",
        .placeStore: "地点 / 商店",
        .customerDetails: "客户详情",
        .customerAddress: "客户地址（可选）",
        .issuerAccount: "开具账户",
        .notePageTwoLabel: "备注（第 2 页）",
        .prefilledFooters: "预设页脚",
        .footerOneDefault: "页脚（第 1 页）",
        .footerTwoDefault: "页脚（第 2 页）",
        .lockFooterOne: "锁定第 1 页页脚",
        .lockFooterTwo: "锁定第 2 页页脚",
        .footerLockedHint: "已锁定：新收据始终使用此页脚。",
        .gotIt: "知道了",
        .infoDiscountBody: "可选择无、小计的百分比或固定金额。折扣在计税前扣除。",
        .infoTaxBody: "在折扣之后加收的税率。留空表示不收税。",
        .infoCashBody: "客户实付金额。找零根据合计金额计算。",
        .infoScannerBody: "拍摄纸质收据，或从相册中选择。应用会通过 AI（Gemini）读取并填写表单。保存前请核对详情。",
        .infoDetailsBody: "本收据的商店、客户、商品和付款信息。可手动填写，也可扫描纸质收据自动填写。",
        .switchLanguageTitle: "切换语言？",
        .switchLanguageBody: "整个应用将立即切换。您的收据和设置会保留。",
        .switchLanguageConfirm: "切换",
        .switchLanguageCancel: "取消",
        .infoUrduLanguage: "以乌尔都语显示应用（从右到左）。关闭即可恢复英文。",
        .infoLockFooter: "新收据始终使用此页脚，且在收据上不可编辑。",
        .lockSignature: "锁定签名板",
        .infoLockSignature: "阻止触摸签名板，以免已签名的收据被意外标记。",
        .extraFees: "额外 / 其他费用",
        .infoExtraFees: "配送、包装或服务费等非税费用。将计入总额。",
        .scanning: "扫描",
        .showTaxBreakdown: "分别显示每项税费",
        .infoShowTaxBreakdown: "当扫描的收据包含多项税费时，逐项列出各自的税率。关闭则显示合并的一行税费。",
        .includeScanFees: "加入扫描收据中的费用",
        .infoIncludeScanFees: "从扫描收据中读取的配送、包装或服务费将计入总额。关闭则不计入。",
        .bulkTitle: "批量扫描",
        .bulkHint: "最多选择 10 张收据照片。每张都会通过 AI 读取，之后您可以核对并保存。",
        .bulkPick: "选择收据",
        .bulkClear: "清除",
        .bulkSave: "全部保存",
        .bulkEdit: "编辑此收据",
        .bulkWaiting: "等待中",
        .bulkScanning: "扫描中…",
        .bulkDone: "已扫描",
        .bulkFailed: "无法读取",
        .bulkAllDone: "全部完成",
        .bulkEtaCalculating: "正在估算时间…",
        .bulkEtaMinutes: "约剩 %d 分钟",
        .bulkEtaSeconds: "约剩 %d 秒",
        .bulkProgress: "已完成 %d / %d",
        .bulkReceiptNumber: "收据 %d",
        .bulkScanTile: "批量扫描",
        .allowBulkCellular: "允许在移动数据下批量扫描",
        .infoAllowBulkCellular: "关闭时，批量扫描会在移动数据下暂停，Wi-Fi 恢复后继续。开启后也可使用移动数据扫描。",
        .infoBulk: "使用 AI 最多扫描 10 张收据照片。需要网络连接：Wi-Fi 可用；除非您在设置中关闭，否则移动数据也可用。应用打开时，扫描进度会显示在灵动岛中。",
        .bulkNetworkNote: "需要 Wi-Fi 或移动数据。可在设置中关闭移动数据。",
        .bulkWaitingNetwork: "正在等待 Wi-Fi，或等待设置中允许使用移动数据…",
        .appSounds: "应用音效",
        .infoAppSounds: "诡异音效和背景音乐。关闭即可静音。",
        .aiSubtitle: "询问收据和汇率",
        .aiEmptyTitle: "询问您的账目",
        .aiSuggest1: "我这个月在杂货上花了多少钱？",
        .aiSuggest2: "今天 500 美元等于多少巴基斯坦卢比？",
        .aiSuggest3: "显示我最近的 5 张收据",
        .aiNewChat: "新对话",
        .aiHistory: "最近对话",
        .aiHistoryEmpty: "暂无对话。您的对话将显示在这里。",
        .aiModelInfo: "由 Google Gemini（%@）提供支持。如果模型繁忙，应用会自动切换到上一个模型。",
        .aiDisclaimer: "这是一个 AI，可能会出错。本体验所使用的模型为 Google Inc. 的 Gemini。",
        .aiVoice: "语音提问",
        .aiListening: "正在聆听…点击麦克风停止",
        .aiTitle: "问 AI",
        .aiHint: "询问您的收据和汇率",
        .aiPlaceholder: "输入您的问题",
        .aiSend: "发送",
        .aiThinking: "思考中…",
        .aiError: "抱歉，目前无法获得回答。请再试一次。",
        .splitBill: "分摊账单",
        .splitCustomer1: "客户 1 支付",
        .splitCustomer2: "客户 2 支付",
        .splitSummary: "客户 1：%@ · 客户 2：%@",
        .each: "每人",
        .issuedBy: "开具人",
        .accountEmail: "账户邮箱",
        .noteTwoPrivateHint: "备注 1 打印在两页上。备注 2、客户电话和邮箱、已保存的位置以及开具账户仅打印在第 2 页。",
        .cloudBackupAndSync: "云备份与同步",
        .syncNow: "立即同步",
        .backUpNow: "立即备份",
        .backingUp: "正在备份…",
        .backupReady: "备份已就绪",
        .backupFailed: "备份失败",
        .backupNeedsNoAccount: "将文件保存到本设备，无需账户。",
        .scannerHint: "拍摄任意纸质收据，扫描器会为您解析并填写表单。",
        .signHere: "在此签名",
        .applePencilOnly: "仅限 Apple Pencil",
        .totalWithoutDiscount: "未扣折扣的合计",
        .totalWithoutTax: "未计税的合计",
        .searchCurrencies: "搜索货币",
        .iranianToman: "伊朗托曼",
        .currencyCodeExample: "代码（例如 AUD）",
        .currencySymbol: "符号",
        .removePasscode: "删除密码",
        .clearSignature: "清除签名",
        .receiptsOnThisDevice: "本设备上的收据",
        .products: "商品",
        .priceList: "价目表",
        .addNewProduct: "添加新商品",
        .editProduct: "编辑商品",
        .searchProducts: "搜索商品…",
        .barcode: "条形码",
        .barcodeInUse: "已被使用于",
        .stock: "库存",
        .lowStock: "库存不足",
        .sellValue: "销售价值",
        .unit: "单位",
        .filterAll: "全部",
        .filterActive: "有效",
        .noProductsYet: "暂无商品",
        .noProductsHint: "扫描条形码或手动添加，以建立商品目录。",
        .markupTools: "标注工具",
        .pageLabel: "页",
        .addNote: "添加备注",
        .websitePage: "网站",
        .newsUpdates: "新闻与更新",
        .downloadPage: "下载",
        .supportPage: "支持",
        .privacyPolicy: "隐私政策",
        .termsOfUse: "使用条款",
        .trademarksPage: "商标",
        .explore: "探索 Cash Memer",
        .supportAndLegal: "支持与法律",
        .platformMobile: "iPhone 与 iPad",
        .platformWearables: "Apple Watch",
        .platformSpatial: "空间计算",
        .platformDriving: "CarPlay 与驾驶",
        .platformLanguages: "语言",
        .platformWeb: "网页应用",
        .syncing: "正在同步…",
        .syncFailed: "同步失败",
        .connected: "已连接",
        .notConnected: "未连接",
        .done: "完成",
        .save: "保存",
        .retry: "重试",
        .ok: "好",
    ]
}
