import Foundation

extension L10n {
    static let urdu: [Key: String] = [
        .appName: "کیش میمر",
        .appTagline: "پروفیشنل رسید آرگنائزر",

        .newReceipt: "رسید بنائیں",
        .history: "ریکارڈز",
        .dashboard: "ڈیش بورڈ",
        .scan: "اسکین",
        .rates: "شرحیں",
        .settings: "ترتیبات",
        .members: "ممبران",
        .archive: "آرکائیو",
        .more: "مزید",

        .aiReceiptScanner: "اے آئی رسید اسکینر (جیمنی)",
        .gallery: "گیلری",
        .camera: "کیمرہ",
        .scanBarcode: "بارکوڈ اسکین کریں",
        .viewScanHistory: "اسکین ہسٹری دیکھیں",
        .receiptDetails: "رسید کی تفصیلات",
        .titleField: "عنوان",
        .placeStoreName: "جگہ / اسٹور کا نام",
        .address: "پتہ",
        .locationAddressGPS: "مقام کا پتہ (جی پی ایس)",
        .currency: "کرنسی",
        .category: "زمرہ",
        .paymentType: "ادائیگی کی قسم",
        .selectMember: "ممبر منتخب کریں",
        .customerName: "کسٹمر کا نام",
        .customerPhone: "کسٹمر کا فون (اختیاری)",
        .customerEmail: "کسٹمر کا ای میل (اختیاری)",
        .addItems: "اشیاء شامل کریں",
        .itemName: "شے کا نام",
        .quantity: "تعداد",
        .price: "قیمت",
        .unitPrice: "فی یونٹ قیمت",
        .total: "کل",
        .item: "شے",
        .discountAndTax: "رعایت اور ٹیکس",
        .discountType: "رعایت کی قسم",
        .taxPercentOptional: "ٹیکس ٪ (اختیاری)",
        .notes: "نوٹس",
        .notesPageTwo: "نوٹس (صفحہ ۲)",
        .livePreview: "لائیو پیش منظر",
        .digitalSignature: "ڈیجیٹل دستخط",
        .signatureCaptured: "محفوظ ہو گئے",
        .signatureHint: "مجاز دستخط کامیابی سے لاگو ہو گئے",
        .saveAsDefaultSignature: "بطور ڈیفالٹ دستخط محفوظ کریں",
        .clearAndRedraw: "مٹائیں اور دوبارہ بنائیں",
        .clear: "صاف کریں",
        .generate: "بنائیں",

        .cashMemo: "کیش میمو",
        .receiptNo: "رسید نمبر",
        .date: "تاریخ",
        .time: "وقت",
        .method: "طریقہ",
        .customer: "کسٹمر",
        .subtotal: "ذیلی میزان",
        .grandTotal: "کل میزان",
        .discount: "رعایت",
        .tax: "ٹیکس",
        .cashGiven: "دی گئی رقم",
        .changeAmount: "واپسی کی رقم",
        .note: "نوٹ",
        .savedLocation: "محفوظ مقام",
        .gps: "جی پی ایس",
        .authorizedSignature: "مجاز دستخط",
        .scanQRForDetails: "تفصیلات کے لیے کیو آر کوڈ اسکین کریں",
        .thankYouForShopping: "خریداری کا شکریہ!",

        .searchReceipts: "رسیدیں تلاش کریں",
        .noReceiptsYet: "ابھی کوئی رسید نہیں",
        .noReceiptsHint: "بنائی گئی رسیدیں یہاں دکھائی دیں گی۔",
        .archived: "آرکائیو شدہ",
        .unarchive: "آرکائیو سے نکالیں",
        .delete: "حذف کریں",
        .share: "شیئر کریں",
        .duplicate: "نقل بنائیں",

        .periodToday: "آج",
        .periodWeek: "ہفتہ",
        .periodMonth: "مہینہ",
        .periodYear: "سال",
        .periodCustom: "حسبِ ضرورت",
        .invoices: "رسیدیں",
        .topStore: "نمایاں اسٹور",
        .thisMonth: "اس مہینے",
        .avgReceipt: "اوسط رسید",
        .totalItems: "کل اشیاء",
        .topCategory: "نمایاں زمرہ",
        .revenueTrend: "آمدنی کا رجحان",
        .insights: "بصیرت",
        .notEnoughData: "اس مدت کے لیے ابھی کافی ڈیٹا نہیں ہے",
        .noDataForPeriod: "اس مدت کے لیے کوئی ڈیٹا نہیں",
        .liveExchangeRates: "لائیو زرِ مبادلہ کی شرحیں",
        .updatedAt: "اپ ڈیٹ",
        .refresh: "تازہ کریں",

        .quickOverview: "فوری جائزہ",
        .todaysSales: "آج کی سیلز",
        .todaysRevenue: "آج کی آمدنی",
        .totalProducts: "کل پراڈکٹس",
        .scansToday: "آج کی اسکین",
        .online: "آن لائن",
        .offline: "آف لائن",
        .rateAPI: "ریٹ API حالت",
        .weather: "موسم",
        .ratesAt: "شرحیں",

        .membersDirectory: "ممبران کی فہرست",
        .addMember: "ممبر شامل کریں",
        .editMember: "ممبر میں ترمیم کریں",
        .exportMembers: "ممبران برآمد کریں",
        .name: "نام",
        .phone: "فون",
        .email: "ای میل",
        .noMembersYet: "ابھی کوئی ممبر نہیں",
        .noMembersHint: "ممبر شامل کریں تاکہ رسیدوں میں ان کی تفصیلات دوبارہ استعمال ہوں۔",

        .appearance: "ظاہری شکل",
        .urduLanguage: "اردو زبان",
        .theme: "تھیم",
        .themeSystem: "سسٹم",
        .themeLight: "روشن",
        .themeDark: "تاریک",
        .security: "سیکیورٹی",
        .appLock: "ایپ لاک",
        .appLockHint: "ایپ کو محفوظ رکھنے کے لیے پاس کوڈ یا فنگر پرنٹ فعال کریں۔ ایپ بند کر کے دوبارہ کھولنے کے لیے فنگر پرنٹ یا پاس کوڈ درکار ہوگا۔",
        .biometrics: "بایومیٹرکس",
        .customPasscodeLock: "کسٹم پاس کوڈ لاک",
        .customPasscodeHint: "ایک کسٹم پاس کوڈ مقرر کریں جو بطور متبادل کی چین میں محفوظ رہتا ہے۔",
        .enterNewPasscode: "نیا پاس کوڈ درج کریں",
        .confirmNewPasscode: "نئے پاس کوڈ کی تصدیق کریں",
        .cancel: "منسوخ",
        .update: "اپڈیٹ کریں",
        .passcodeMismatch: "پاس کوڈ آپس میں نہیں ملتے۔",
        .passcodeTooShort: "پاس کوڈ کم از کم ۴ ہندسوں کا ہونا چاہیے۔",
        .signature: "دستخط",
        .createSignature: "دستخط بنائیں",
        .removeSignature: "دستخط ہٹائیں",
        .customCurrency: "کسٹم کرنسی",
        .addThisCurrency: "یہ کرنسی شامل کریں",
        .googleSignIn: "گوگل سائن ان",
        .googleSignInHint: "گوگل اکاؤنٹ سے سائن ان کریں تاکہ بیک اپ خود بخود اپلوڈ ہو جائے۔",
        .signInWithGoogle: "گوگل سے سائن ان کریں",
        .signOut: "سائن آؤٹ",
        .backupAndRestore: "بیک اپ اور ریسٹور",
        .uploadBackup: "بیک اپ کلاؤڈ پر اپلوڈ کریں",
        .shareBackupFile: "بیک اپ فائل شیئر کریں",
        .restoreFromBackup: "بیک اپ سے ریسٹور کریں",
        .dataManagement: "ڈیٹا کا انتظام",
        .deleteAllReceipts: "تمام رسیدیں حذف کریں",
        .deleteAllConfirm: "اس سے اس ڈیوائس کی تمام رسیدیں مستقل طور پر حذف ہو جائیں گی۔ اسے واپس نہیں کیا جا سکتا۔",
        .information: "معلومات",
        .version: "ورژن",
        .app: "ایپ",
        .contactUs: "ہم سے رابطہ کریں!",
        .mail: "ای میل",
        .web: "ویب",
        .social: "سوشل",
        .contactResponseNote: "ہم ہمیشہ آپ کی مدد اور تجاویز سن کر خوش ہوتے ہیں۔",

        .categoryShopping: "خریداری",
        .categoryGroceries: "گروسری",
        .categoryFood: "کھانا",
        .categoryFuel: "ایندھن",
        .categoryTravel: "سفر",
        .categoryUtilities: "یوٹیلیٹیز",
        .categoryHealth: "صحت",
        .categoryEducation: "تعلیم",
        .categoryServices: "خدمات",
        .categoryOther: "دیگر",

        .methodCash: "نقد",
        .methodApplePay: "ایپل پے",
        .methodCard: "کارڈ",
        .methodBankTransfer: "بینک ٹرانسفر",
        .methodEasypaisa: "ایزی پیسہ",
        .methodJazzcash: "جاز کیش",
        .methodCredit: "ادھار",

        .discountNone: "کوئی نہیں",
        .discountPercentage: "فیصد",
        .discountFixed: "مقررہ رقم",

        .openOnIPhoneToSync: "رسیدیں سنک کرنے کے لیے اپنے آئی فون پر کیش میمر کھولیں",
        .syncedJustNow: "ابھی سنک ہوا",

        .pageTwo: "صفحہ ۲",
        .placeStore: "جگہ/اسٹور",
        .customerDetails: "کسٹمر کی تفصیلات",
        .customerAddress: "کسٹمر کا پتہ (اختیاری)",
        .issuerAccount: "جاری کنندہ اکاؤنٹ",
        .notePageTwoLabel: "نوٹ (صفحہ ۲)",
        .each: "فی عدد",
        .issuedBy: "جاری کنندہ",
        .accountEmail: "اکاؤنٹ ای میل",
        .noteTwoPrivateHint: "نوٹ ۱ دونوں صفحات پر چھپتا ہے۔ نوٹ ۲، کسٹمر کا فون اور ای میل، محفوظ مقام اور جاری کنندہ اکاؤنٹ صرف صفحہ ۲ پر چھپتے ہیں۔",

        .cloudBackupAndSync: "کلاؤڈ بیک اپ اور سنک",
        .syncing: "سنک ہو رہا ہے…",
        .syncFailed: "سنک ناکام",
        .connected: "منسلک",
        .notConnected: "منسلک نہیں",
        .done: "مکمل",
        .save: "محفوظ کریں",
        .retry: "دوبارہ کوشش کریں",
        .ok: "ٹھیک ہے"
    ]
}
