import Foundation

extension L10n {
    static let english: [Key: String] = [
        .appName: "Cash Memer",
        .appTagline: "Professional Receipt Organizer",

        .newReceipt: "New Receipt",
        .history: "History",
        .dashboard: "Dashboard",
        .scan: "Scan",
        .rates: "Rates",
        .settings: "Settings",
        .members: "Members",
        .archive: "Archive",
        .more: "More",

        .aiReceiptScanner: "AI Receipt Scanner (Gemini)",
        .gallery: "Gallery",
        .camera: "Camera",
        .scanBarcode: "Scan Barcode",
        .viewScanHistory: "View Scan History",
        .receiptDetails: "Receipt Details",
        .titleField: "Title",
        .placeStoreName: "Place / Store Name",
        .address: "Address",
        .locationAddressGPS: "Location Address (GPS)",
        .currency: "Currency",
        .category: "Category",
        .paymentType: "Payment Type",
        .selectMember: "Select Member",
        .customerName: "Customer Name",
        .customerPhone: "Customer Phone (Optional)",
        .customerEmail: "Customer Email (Optional)",
        .addItems: "Add Items",
        .itemName: "Item Name",
        .quantity: "Qty",
        .price: "Price",
        .unitPrice: "Unit Price",
        .total: "Total",
        .item: "Item",
        .discountAndTax: "Discount & Tax",
        .discountType: "Discount Type",
        .taxPercentOptional: "Tax % (optional)",
        .notes: "Notes",
        .notesPageTwo: "Notes (Page 2)",
        .livePreview: "Live Preview",
        .digitalSignature: "Digital Signature",
        .signatureCaptured: "Captured",
        .signatureHint: "Authorized signature applied successfully",
        .saveAsDefaultSignature: "Save as Default Signature",
        .clearAndRedraw: "Clear & Redraw",
        .clear: "Clear",
        .generate: "Generate",

        .cashMemo: "CASH MEMO",
        .receiptNo: "Receipt No",
        .date: "Date",
        .time: "Time",
        .method: "Method",
        .customer: "Customer",
        .subtotal: "Subtotal",
        .grandTotal: "GRAND TOTAL",
        .discount: "Discount",
        .tax: "Tax",
        .cashGiven: "Cash Given",
        .changeAmount: "Change Amount",
        .note: "Note",
        .savedLocation: "Saved Location",
        .gps: "GPS",
        .authorizedSignature: "Authorized Signature",
        .scanQRForDetails: "Scan QR Code for details",
        .thankYouForShopping: "Thank you for shopping!",

        .searchReceipts: "Search receipts",
        .noReceiptsYet: "No receipts yet",
        .noReceiptsHint: "Generated receipts will appear here.",
        .archived: "Archived",
        .unarchive: "Unarchive",
        .delete: "Delete",
        .share: "Share",
        .duplicate: "Duplicate",

        .periodToday: "Today",
        .periodWeek: "Week",
        .periodMonth: "Month",
        .periodYear: "Year",
        .periodCustom: "Custom",
        .invoices: "Invoices",
        .topStore: "Top Store",
        .thisMonth: "This Month",
        .avgReceipt: "Avg. Receipt",
        .totalItems: "Total Items",
        .topCategory: "Top Category",
        .revenueTrend: "Revenue Trend",
        .insights: "Insights",
        .notEnoughData: "Not enough data yet for this period",
        .noDataForPeriod: "No data for this period",
        .liveExchangeRates: "Live Exchange Rates",
        .updatedAt: "Updated",
        .refresh: "Refresh",

        .quickOverview: "Quick Overview",
        .todaysSales: "Today's Sales",
        .todaysRevenue: "Today's Revenue",
        .totalProducts: "Total Products",
        .scansToday: "Scans Today",
        .online: "Online",
        .offline: "Offline",
        .rateAPI: "Rate API",
        .weather: "Weather",
        .ratesAt: "Rates",

        .membersDirectory: "Members Directory",
        .addMember: "Add Member",
        .editMember: "Edit Member",
        .exportMembers: "Export Members",
        .name: "Name",
        .phone: "Phone",
        .email: "Email",
        .noMembersYet: "No members yet",
        .noMembersHint: "Add a member to reuse their details on receipts.",

        .appearance: "Appearance",
        .urduLanguage: "Urdu Language",
        .theme: "Theme",
        .themeSystem: "System",
        .themeLight: "Light",
        .themeDark: "Dark",
        .security: "Security",
        .appLock: "App Lock",
        .appLockHint: "Enable a passcode or fingerprint to keep the app secure. You will need Face ID, Touch ID or your passcode to reopen the app after closing it.",
        .biometrics: "Biometrics",
        .customPasscodeLock: "Custom Passcode Lock",
        .customPasscodeHint: "Set a custom passcode that is stored securely in the Keychain as a fallback.",
        .enterNewPasscode: "Enter New Passcode",
        .confirmNewPasscode: "Confirm New Passcode",
        .cancel: "Cancel",
        .update: "Update",
        .passcodeMismatch: "Passcodes do not match.",
        .passcodeTooShort: "Passcode must be at least 4 digits.",
        .signature: "Signature",
        .createSignature: "Create Signature",
        .removeSignature: "Remove Signature",
        .customCurrency: "Custom Currency",
        .addThisCurrency: "Add This Currency",
        .googleSignIn: "Google Sign-In",
        .googleSignInHint: "Sign in with a Google account so backups upload automatically.",
        .signInWithGoogle: "Sign in with Google",
        .signOut: "Sign Out",
        .backupAndRestore: "Backup & Restore",
        .uploadBackup: "Upload Backup to Cloud",
        .shareBackupFile: "Share Backup File",
        .restoreFromBackup: "Restore from Backup",
        .dataManagement: "Data Management",
        .deleteAllReceipts: "Delete All Receipts",
        .deleteAllConfirm: "This permanently deletes every receipt on this device. It cannot be undone.",
        .information: "Information",
        .version: "Version",
        .app: "App",
        .contactUs: "Contact Us!",
        .mail: "Mail",
        .web: "Web",
        .social: "Social",
        .contactResponseNote: "We will try to respond as quickly as possible.",

        .categoryShopping: "Shopping",
        .categoryGroceries: "Groceries",
        .categoryFood: "Food",
        .categoryFuel: "Fuel",
        .categoryTravel: "Travel",
        .categoryUtilities: "Utilities",
        .categoryHealth: "Health",
        .categoryEducation: "Education",
        .categoryServices: "Services",
        .categoryOther: "Other",

        .methodCash: "Cash",
        .methodApplePay: "Apple Pay",
        .methodCard: "Card",
        .methodBankTransfer: "Bank Transfer",
        .methodEasypaisa: "Easypaisa",
        .methodJazzcash: "JazzCash",
        .methodCredit: "Credit",

        .discountNone: "None",
        .discountPercentage: "Percentage",
        .discountFixed: "Fixed Amount",

        .openOnIPhoneToSync: "Open Cash Memer on your iPhone to sync receipts",
        .openOnIPhoneToSyncRates: "Open Cash Memer on your iPhone to sync rates",
        .syncedJustNow: "Synced just now",

        .pageTwo: "Page 2",
        .placeStore: "Place/Store",
        .customerDetails: "Customer Details",
        .customerAddress: "Customer Address (Optional)",
        .issuerAccount: "Issuer Account",
        .notePageTwoLabel: "Note (Page 2)",
        .prefilledFooters: "Prefilled footers",
        .footerOneDefault: "Footer (Page 1)",
        .footerTwoDefault: "Footer (Page 2)",
        .lockFooterOne: "Lock Page 1 footer",
        .lockFooterTwo: "Lock Page 2 footer",
        .footerLockedHint: "Locked: new receipts always use this footer.",
        .gotIt: "Got it",
        .infoDiscountBody: "Choose None, a percentage of the subtotal, or a fixed amount. The discount is taken off before tax.",
        .infoTaxBody: "The tax rate added after any discount. Leave it empty for no tax.",
        .infoCashBody: "The amount the customer paid. The change is worked out from the total.",
        .infoScannerBody: "Photograph a paper receipt, or pick one from your gallery. The app reads it with AI (Gemini) and fills in the form. Check the details before saving.",
        .infoDetailsBody: "The store, customer, items and payment for this receipt. Fill them in by hand, or scan a paper receipt to fill them in.",
        .switchLanguageTitle: "Switch language?",
        .switchLanguageBody: "The whole app switches straight away. Your receipts and settings are kept.",
        .switchLanguageConfirm: "Switch",
        .switchLanguageCancel: "Cancel",
        .infoUrduLanguage: "Shows the app in Urdu, right to left. Turn it off to go back to English.",
        .infoLockFooter: "New receipts always use this footer, and it cannot be edited on the receipt.",
        .lockSignature: "Lock signature pad",
        .infoLockSignature: "Stops touches on the signature pad, so a signed memo cannot be marked by accident.",
        .extraFees: "Extra / other fees",
        .infoExtraFees: "Delivery, packing or service fees that are not tax. They are added to the total.",
        .scanning: "Scanning",
        .showTaxBreakdown: "Show each tax separately",
        .infoShowTaxBreakdown: "When a scanned receipt has several taxes, list each one with its own percentage. Off shows one combined tax line.",
        .includeScanFees: "Add fees from scanned receipts",
        .infoIncludeScanFees: "Delivery, packing or service fees read from a scanned receipt are added to the total. Turn this off to leave them out.",
        .bulkTitle: "Bulk scan",
        .bulkHint: "Choose up to 10 receipt photos. Each one is read with AI, then you can check and save them.",
        .bulkPick: "Choose receipts",
        .bulkClear: "Clear",
        .bulkSave: "Save all",
        .bulkEdit: "Edit this receipt",
        .bulkWaiting: "Waiting",
        .bulkScanning: "Scanning…",
        .bulkDone: "Scanned",
        .bulkFailed: "Could not read",
        .bulkAllDone: "All done",
        .bulkEtaCalculating: "Estimating time…",
        .bulkEtaMinutes: "About %d min left",
        .bulkEtaSeconds: "About %d sec left",
        .bulkProgress: "%d of %d done",
        .bulkReceiptNumber: "Receipt %d",
        .bulkScanTile: "Bulk scan",
        .allowBulkCellular: "Allow bulk scanning on mobile data",
        .infoAllowBulkCellular: "When off, bulk scanning pauses on mobile data and carries on once Wi-Fi is back. Turn it on to scan over mobile data too.",
        .infoBulk: "Scans up to 10 receipt photos with AI. It needs an internet connection: Wi-Fi works, and mobile data works unless you turn it off in Settings. Scanning shows progress in the Dynamic Island while the app is open.",
        .bulkNetworkNote: "Needs Wi-Fi or mobile data. Mobile data can be turned off in Settings.",
        .bulkWaitingNetwork: "Waiting for Wi-Fi, or for mobile data to be allowed in Settings…",
        .each: "each",
        .issuedBy: "Issued By",
        .accountEmail: "Account Email",
        .noteTwoPrivateHint: "Note 1 prints on both pages. Note 2, the customer's phone and email, the saved location and the issuing account print on page 2 only.",

        .cloudBackupAndSync: "Cloud Backup & Sync",
        .syncNow: "Sync Now",
        .backUpNow: "Back Up Now",
        .backingUp: "Backing up…",
        .backupReady: "Backup ready",
        .backupFailed: "Backup failed",
        .backupNeedsNoAccount: "Saves a file to this device. No account needed.",
        .scannerHint: "Take a picture of any paper receipt, and the scanner will parse it and fill the form for you.",
        .signHere: "Sign here",
        .applePencilOnly: "Apple Pencil Only",
        .totalWithoutDiscount: "Total without Discount",
        .totalWithoutTax: "Total without Tax",
        .searchCurrencies: "Search currencies",
        .iranianToman: "Iranian Toman",
        .currencyCodeExample: "Code (e.g. AUD)",
        .currencySymbol: "Symbol",
        .removePasscode: "Remove Passcode",
        .clearSignature: "Clear Signature",
        .receiptsOnThisDevice: "receipts on this device",
        .products: "Products",
        .priceList: "Price List",
        .addNewProduct: "Add New Product",
        .editProduct: "Edit Product",
        .searchProducts: "Search products…",
        .barcode: "Barcode",
        .barcodeInUse: "Already used by",
        .stock: "Stock",
        .lowStock: "low stock",
        .sellValue: "Sell value",
        .unit: "Unit",
        .filterAll: "All",
        .filterActive: "Active",
        .noProductsYet: "No products yet",
        .noProductsHint: "Scan a barcode or add one by hand to build the catalogue.",
        .markupTools: "Markup tools",
        .pageLabel: "Page",
        .addNote: "Add a note",
        .websitePage: "Website",
        .newsUpdates: "News & Updates",
        .downloadPage: "Download",
        .supportPage: "Support",
        .privacyPolicy: "Privacy Policy",
        .termsOfUse: "Terms of Use",
        .trademarksPage: "Trademarks",
        .explore: "Explore Cash Memer",
        .supportAndLegal: "Support & Legal",
        .platformMobile: "iPhone & iPad",
        .platformWearables: "Apple Watch",
        .platformSpatial: "Spatial",
        .platformDriving: "CarPlay & Driving",
        .platformLanguages: "Languages",
        .platformWeb: "Web App",
        .syncing: "Syncing…",
        .syncFailed: "Sync Failed",
        .connected: "Connected",
        .notConnected: "Not Connected",
        .done: "Done",
        .save: "Save",
        .retry: "Retry",
        .ok: "OK"
    ]
}
