import Foundation

extension L10n {
    static let english: [Key: String] = [
        .appName: "Cash Memer",
        .appTagline: "Professional Receipt Organizer",

        .newReceipt: "New Receipt",
        .history: "History",
        .dashboard: "Dashboard",
        .scan: "Scan",
        .rates: "Rates",
        .settings: "Settings",
        .members: "Members",
        .archive: "Archive",
        .more: "More",

        .aiReceiptScanner: "AI Receipt Scanner (Gemini)",
        .gallery: "Gallery",
        .camera: "Camera",
        .scanBarcode: "Scan Barcode",
        .viewScanHistory: "View Scan History",
        .receiptDetails: "Receipt Details",
        .titleField: "Title",
        .placeStoreName: "Place / Store Name",
        .address: "Address",
        .locationAddressGPS: "Location Address (GPS)",
        .currency: "Currency",
        .category: "Category",
        .paymentType: "Payment Type",
        .selectMember: "Select Member",
        .customerName: "Customer Name",
        .customerPhone: "Customer Phone (Optional)",
        .customerEmail: "Customer Email (Optional)",
        .addItems: "Add Items",
        .itemName: "Item Name",
        .quantity: "Qty",
        .price: "Price",
        .unitPrice: "Unit Price",
        .total: "Total",
        .item: "Item",
        .discountAndTax: "Discount & Tax",
        .discountType: "Discount Type",
        .taxPercentOptional: "Tax % (optional)",
        .notes: "Notes",
        .notesPageTwo: "Notes (Page 2)",
        .livePreview: "Live Preview",
        .digitalSignature: "Digital Signature",
        .signatureCaptured: "Captured",
        .signatureHint: "Authorized signature applied successfully",
        .saveAsDefaultSignature: "Save as Default Signature",
        .clearAndRedraw: "Clear & Redraw",
        .clear: "Clear",
        .generate: "Generate",

        .cashMemo: "CASH MEMO",
        .receiptNo: "Receipt No",
        .date: "Date",
        .time: "Time",
        .method: "Method",
        .customer: "Customer",
        .subtotal: "Subtotal",
        .grandTotal: "GRAND TOTAL",
        .discount: "Discount",
        .tax: "Tax",
        .cashGiven: "Cash Given",
        .changeAmount: "Change Amount",
        .note: "Note",
        .savedLocation: "Saved Location",
        .gps: "GPS",
        .authorizedSignature: "Authorized Signature",
        .scanQRForDetails: "Scan QR Code for details",
        .thankYouForShopping: "Thank you for shopping!",

        .searchReceipts: "Search receipts",
        .noReceiptsYet: "No receipts yet",
        .noReceiptsHint: "Generated receipts will appear here.",
        .archived: "Archived",
        .unarchive: "Unarchive",
        .delete: "Delete",
        .share: "Share",
        .duplicate: "Duplicate",

        .periodToday: "Today",
        .periodWeek: "Week",
        .periodMonth: "Month",
        .periodYear: "Year",
        .periodCustom: "Custom",
        .invoices: "Invoices",
        .topStore: "Top Store",
        .thisMonth: "This Month",
        .avgReceipt: "Avg. Receipt",
        .totalItems: "Total Items",
        .topCategory: "Top Category",
        .revenueTrend: "Revenue Trend",
        .insights: "Insights",
        .notEnoughData: "Not enough data yet for this period",
        .noDataForPeriod: "No data for this period",
        .liveExchangeRates: "Live Exchange Rates",
        .updatedAt: "Updated",
        .refresh: "Refresh",

        .quickOverview: "Quick Overview",
        .todaysSales: "Today's Sales",
        .todaysRevenue: "Today's Revenue",
        .totalProducts: "Total Products",
        .scansToday: "Scans Today",
        .online: "Online",
        .offline: "Offline",
        .rateAPI: "Rate API",
        .weather: "Weather",
        .ratesAt: "Rates",

        .membersDirectory: "Members Directory",
        .addMember: "Add Member",
        .editMember: "Edit Member",
        .exportMembers: "Export Members",
        .name: "Name",
        .phone: "Phone",
        .email: "Email",
        .noMembersYet: "No members yet",
        .noMembersHint: "Add a member to reuse their details on receipts.",

        .appearance: "Appearance",
        .urduLanguage: "Urdu Language",
        .theme: "Theme",
        .themeSystem: "System",
        .themeLight: "Light",
        .themeDark: "Dark",
        .security: "Security",
        .appLock: "App Lock",
        .appLockHint: "Enable a passcode or fingerprint to keep the app secure. You will need Face ID, Touch ID or your passcode to reopen the app after closing it.",
        .biometrics: "Biometrics",
        .customPasscodeLock: "Custom Passcode Lock",
        .customPasscodeHint: "Set a custom passcode that is stored securely in the Keychain as a fallback.",
        .enterNewPasscode: "Enter New Passcode",
        .confirmNewPasscode: "Confirm New Passcode",
        .cancel: "Cancel",
        .update: "Update",
        .passcodeMismatch: "Passcodes do not match.",
        .passcodeTooShort: "Passcode must be at least 4 digits.",
        .signature: "Signature",
        .createSignature: "Create Signature",
        .removeSignature: "Remove Signature",
        .customCurrency: "Custom Currency",
        .addThisCurrency: "Add This Currency",
        .googleSignIn: "Google Sign-In",
        .googleSignInHint: "Sign in with a Google account so backups upload automatically.",
        .signInWithGoogle: "Sign in with Google",
        .signOut: "Sign Out",
        .backupAndRestore: "Backup & Restore",
        .uploadBackup: "Upload Backup to Cloud",
        .shareBackupFile: "Share Backup File",
        .restoreFromBackup: "Restore from Backup",
        .dataManagement: "Data Management",
        .deleteAllReceipts: "Delete All Receipts",
        .deleteAllConfirm: "This permanently deletes every receipt on this device. It cannot be undone.",
        .information: "Information",
        .version: "Version",
        .app: "App",
        .contactUs: "Contact Us!",
        .mail: "Mail",
        .web: "Web",
        .social: "Social",
        .contactResponseNote: "We will try to respond as quickly as possible.",

        .categoryShopping: "Shopping",
        .categoryGroceries: "Groceries",
        .categoryFood: "Food",
        .categoryFuel: "Fuel",
        .categoryTravel: "Travel",
        .categoryUtilities: "Utilities",
        .categoryHealth: "Health",
        .categoryEducation: "Education",
        .categoryServices: "Services",
        .categoryOther: "Other",

        .methodCash: "Cash",
        .methodApplePay: "Apple Pay",
        .methodCard: "Card",
        .methodBankTransfer: "Bank Transfer",
        .methodEasypaisa: "Easypaisa",
        .methodJazzcash: "JazzCash",
        .methodCredit: "Credit",

        .discountNone: "None",
        .discountPercentage: "Percentage",
        .discountFixed: "Fixed Amount",

        .openOnIPhoneToSync: "Open Cash Memer on your iPhone to sync receipts",
        .openOnIPhoneToSyncRates: "Open Cash Memer on your iPhone to sync rates",
        .syncedJustNow: "Synced just now",

        .pageTwo: "Page 2",
        .placeStore: "Place/Store",
        .customerDetails: "Customer Details",
        .customerAddress: "Customer Address (Optional)",
        .issuerAccount: "Issuer Account",
        .notePageTwoLabel: "Note (Page 2)",
        .each: "each",
        .issuedBy: "Issued By",
        .accountEmail: "Account Email",
        .noteTwoPrivateHint: "Note 1 prints on both pages. Note 2, the customer's phone and email, the saved location and the issuing account print on page 2 only.",

        .cloudBackupAndSync: "Cloud Backup & Sync",
        .syncNow: "Sync Now",
        .backUpNow: "Back Up Now",
        .backingUp: "Backing up…",
        .backupReady: "Backup ready",
        .backupFailed: "Backup failed",
        .backupNeedsNoAccount: "Saves a file to this device. No account needed.",
        .scannerHint: "Take a picture of any paper receipt, and the scanner will parse it and fill the form for you.",
        .signHere: "Sign here",
        .applePencilOnly: "Apple Pencil Only",
        .totalWithoutDiscount: "Total without Discount",
        .totalWithoutTax: "Total without Tax",
        .searchCurrencies: "Search currencies",
        .iranianToman: "Iranian Toman",
        .currencyCodeExample: "Code (e.g. AUD)",
        .currencySymbol: "Symbol",
        .removePasscode: "Remove Passcode",
        .clearSignature: "Clear Signature",
        .syncing: "Syncing…",
        .syncFailed: "Sync Failed",
        .connected: "Connected",
        .notConnected: "Not Connected",
        .done: "Done",
        .save: "Save",
        .retry: "Retry",
        .ok: "OK"
    ]
}
